version: '3.3'
services:
  server:
    build: ./server
    ports:
      - '5000:5000'
    volumes:
      - ./server:/app
      - /app/node_modules
  client:
    build: ./client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - server
